---
title: "trial_number_stats"
author: "CC"
date: "2023-04-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Stats on ERP trial number

setup
```{r echo = FALSE}

library("tidyverse")
library("readxl")

rm(list=ls())
setwd(dir="../data/ERP/raw_data/reprocessed040823")

# read in raw data (provided by Dan) in preparation of constructing LME models -----
data_N2_P2p_375_475 <- read_csv("RATIO_medAD_P2indtrialdata040823.csv", col_names = F) %>%
  rename(subj_num = X1, # rename header according to readme_RATIO_medAD_P2indtrialdata.txt
         KL.cont = X2,
         cond = X3,
         erp.p2p = X4,
         erp.n2 = X5,
         time_point = X6) %>%
  select(subj_num, time_point, KL.cont, cond, erp.p2p, erp.n2) %>%
  group_by(subj_num, time_point, cond) %>%
  mutate(trial_num = row_number()) %>%
  ungroup()

data_N1_P2a <- read_csv("RATIO_medAD_N1indtrialdata040823.csv", col_names = F) %>%
  rename(subj_num = X1, # rename header according to readme_RATIO_medAD_N1indtrialdata.txt
         KL.cont = X2,
         cond = X3,
         erp.n1 = X4,
         erp.p2a = X5,
         time_point = X6) %>%
  select(subj_num, time_point, KL.cont, cond, erp.n1, erp.p2a) %>%
  group_by(subj_num, time_point, cond) %>%
  mutate(trial_num = row_number()) %>%
  ungroup()
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
